<?php

return [
    'Alternative Metal',
    'Ambient Black Metal',
    'Ambient Metal',
    'Atmospheric Black Metal',
    'Avant-Garde Metal',
    'Beatdown Hardcore',
    'Black Metal',
    'Black/Thrash',
    'Blackened Death Metal',
    'Blackened Deathcore',
    'Blackened Thrash Metal',
    'Blackgaze',
    'Brutal Death Metal',
    'Christian Metal',
    'Cinematic Metal',
    'Crabcore',
    'Crust Punk',
    'Crossover Thrash',
    'Cyber Metal',
    'Dark Metal',
    'Death Metal',
    'Death \'n\' Roll',
    'Death/Thrash',
    'Deathcore',
    'Deathgrind',
    'Depressive Suicidal Black Metal (DSBM)',
    'Djent',
    'Doom Metal',
    'Drone Metal',
    'Electronicore',
    'Epic Doom Metal',
    'Easycore',
    'Experimental Metal',
    'Folk Metal',
    'Funeral Doom',
    'Funk Metal',
    'Glam Metal',
    'Goregrind',
    'Gothic Metal',
    'Grindcore',
    'Groove Metal',
    'Hardcore',
    'Hardcore Punk',
    'Heavy Metal',
    'Industrial Death Metal',
    'Industrial Metal',
    'Jazz Metal',
    'Kawaii Metal',
    'Latin Metal',
    'Math Metal',
    'Mathcore',
    'Medieval Metal',
    'Melodic Black Metal',
    'Melodic Brutal Death Metal',
    'Melodic Death Metal',
    'Melodic Metalcore',
    'Metalcore',
    'Metalstep',
    'Neoclassical Metal',
    'Neue Deutsche Härte',
    'Nintendocore',
    'Noise Metal',
    'Nu Metal',
    'NWOBHM',
    'NWOTHM',
    'Old School Death Metal (OSDM)',
    'Oriental Metal',
    'Pagan Metal',
    'Pirate Metal',
    'Pornogrind',
    'Post-Black Metal',
    'Post-Death Metal',
    'Post-Hardcore',
    'Post-Metal',
    'Power Metal',
    'Progressive Death Metal',
    'Progressive Metal',
    'Proto-Metal',
    'Rap Metal',
    'Raw Black Metal',
    'Slavic Pagan Metal',
    'Sludge Metal',
    'Slam Death Metal',
    'Softcore',
    'Southern Metal',
    'Speed Metal',
    'Stoner Metal',
    'Symphonic Black Metal',
    'Symphonic Death Metal',
    'Symphonic Metal',
    'Technical Brutal Death Metal',
    'Technical Death Metal',
    'Technical Metal',
    'Technical Metalcore',
    'Thrash Metal',
    'Traditional Doom Metal',
    'Trap Metal',
    'Unblack Metal',
    'Viking Metal',
    'War Metal',
];
