<?php

return [
    'Alternative Metal',
    'Alternative Rock',
    'Ambient Black Metal',
    'Ambient Metal',
    'Atmospheric Black Metal',
    'Avant-Garde Metal',
    'Bay Area Thrash Metal',
    'Beatdown Hardcore',
    'Black Metal',
    'Black/Thrash',
    'Blackened Death Metal',
    'Blackened Deathcore',
    'Blackened Thrash Metal',
    'Blackgaze',
    'Brutal Death Metal',
    'Celtic Metal',
    'Christian Metal',
    'Cinematic Metal',
    'Crabcore',
    'Crust Punk',
    'Crossover Thrash',
    'Cyber Metal',
    'Dark Metal',
    'Death Metal',
    'Death \'n\' Roll',
    'Death/Thrash',
    'Deathcore',
    'Deathgrind',
    'Depressive Suicidal Black Metal (DSBM)',
    'Djent',
    'Doom Metal',
    'Drone Metal',
    'Electronicore',
    'Electrogrind',
    'Epic Doom Metal',
    'Easycore',
    'Experimental Metal',
    'Folk Metal',
    'Funeral Doom',
    'Funk Metal',
    'Glam Metal',
    'Goregrind',
    'Gothic Metal',
    'Grindcore',
    'Groove Metal',
    'Hardcore',
    'Hard Rock',
    'Hardcore Punk',
    'Heavy Metal',
    'Heavy Thrash Hardcore',
    'Industrial Black Metal',
    'Industrial Death Metal',
    'Industrial Metal',
    'Jazz Metal',
    'Kawaii Metal',
    'Latin Metal',
    'Math Metal',
    'Mathcore',
    'Medieval Metal',
    'Melodic Black Metal',
    'Melodic Brutal Death Metal',
    'Melodic Death Metal',
    'Melodic Metalcore',
    'Metalcore',
    'Metalstep',
    'Modern Hardcore',
    'Modern Metal',
    'Neoclassical Metal',
    'Neue Deutsche Härte',
    'Nintendocore',
    'Noise Metal',
    'Nu Metal',
    'Nu Metalcore',
    'NWOBHM',
    'NWOTHM',
    'Old School Death Metal (OSDM)',
    'Oriental Metal',
    'Pagan Metal',
    'Pirate Metal',
    'Pornogrind',
    'Post-Black Metal',
    'Post-Death Metal',
    'Post-Hardcore',
    'Post-Metal',
    'Power Metal',
    'Progressive Death Metal',
    'Progressive Metal',
    'Progressive Metalcore',
    'Proto-Metal',
    'Rap Metal',
    'Raw Black Metal',
    'Slavic Pagan Metal',
    'Slamming Brutal Death Metal',
    'Sludge Metal',
    'Slam Death Metal',
    'Softcore',
    'Southern Metal',
    'Speed Metal',
    'Stoner Metal',
    'Symphonic Black Metal',
    'Symphonic Death Metal',
    'Symphonic Metal',
    'Technical Brutal Death Metal',
    'Technical Death Metal',
    'Technical Metal',
    'Technical Metalcore',
    'Thrash Metal',
    'Traditional Doom Metal',
    'Trap Metal',
    'Trash Metal',
    'Unblack Metal',
    'Viking Metal',
    'War Metal',
];
