services:
  mysql:
    image: mysql:8
    container_name: groundlink-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: groundlink
      MYSQL_USER: groundlink
      MYSQL_PASSWORD: groundlink
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: groundlink-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: groundlink-backend
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: groundlink
      DB_USERNAME: groundlink
      DB_PASSWORD: groundlink
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: groundlink-frontend
    restart: unless-stopped
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql_data:
